
services:
  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile  # Путь к Dockerfile для server
    volumes:
      - .:/app
      - ./logs:/app/logs
      - air-bin:/root/go/bin
    working_dir: /app
    command: air -c .air.server.toml
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - CGO_ENABLED=0
      - GO111MODULE=on
    networks:
      - metrics-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: praktikum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      GDATA: /var/lib/postgresql/data
    volumes:
      - ./postgresql-data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"

  agent:
    build:
      context: .
      dockerfile: cmd/agent/Dockerfile  # Путь к Dockerfile для agent
    volumes:
      - .:/app
      - ./logs:/app/logs
      - air-bin:/root/go/bin
    working_dir: /app
    command: air -c .air.agent.toml
    ports:
      - "${AGENT_PORT}:${AGENT_PORT}"
    env_file:
      - .env
    environment:
      - CGO_ENABLED=0
      - GO111MODULE=on
    networks:
      - metrics-network

volumes:
  air-bin:

networks:
  metrics-network:
    driver: bridge
