### Send POST request for update metric
POST http://localhost:8083/update
Content-Type: application/json

{
  "id": "PollCount",
  "type": "counter",
  "delta": 1
}

### Send POST request for get metric
POST http://localhost:8080/value/
Content-Type: application/json

{
"id": "PollCount",
"type": "counter"
}

<> 2025-04-16T120540.200.txt

### SEND POST ITER2
POST http://localhost:8080/update/gauge/Alloc/667168

### GET VALUE ITER2
GET http://localhost:8080/value/gauge/Alloc



