package main

import (
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func main() {
	buildVersion := getGitTag()
	buildDate := getBuildDate()
	buildCommit := getGitCommit()

	var sb strings.Builder
	fmt.Fprintf(&sb, "%s", `// Package version содержит функциональность для работы с версией приложения.
// Включает генерацию информации о версии через go generate и функцию для вывода этой информации.

// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/genversion/main.go

package version

const (
`)
	fmt.Fprintf(&sb, "	BuildVersion = %q\n", buildVersion)
	fmt.Fprintf(&sb, "	BuildDate = %q\n", buildDate)
	fmt.Fprintf(&sb, "	BuildCommit = %q\n", buildCommit)
	fmt.Fprintf(&sb, ")")

	generated := []byte(sb.String())
	formatted, err := format.Source(generated)
	if err != nil {
		panic(err)
	}

	projectRoot := findProjectRoot()
	outputPath := filepath.Join(projectRoot, "internal", "version", "version_generated.go")

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		panic(err)
	}

	err = os.WriteFile(outputPath, formatted, 0644)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Build info generated:\n")
	fmt.Printf("  Version: %s\n", buildVersion)
	fmt.Printf("  Date: %s\n", buildDate)
	fmt.Printf("  Commit: %s\n", buildCommit)
}

func findProjectRoot() string {
	currentDir, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	for {
		if _, err := os.Stat(filepath.Join(currentDir, "go.mod")); err == nil {
			return currentDir
		}

		parent := filepath.Dir(currentDir)
		if parent == currentDir {
			panic("go.mod not found in any parent directory")
		}
		currentDir = parent
	}
}

func getGitTag() string {
	cmd := exec.Command("git", "describe", "--tags", "--abbrev=0")
	output, err := cmd.Output()
	if err != nil {
		return "N/A"
	}
	return strings.TrimSpace(string(output))
}

func getBuildDate() string {
	cmd := exec.Command("date", "-u", "+%Y-%m-%d_%H:%M:%S_UTC")
	output, err := cmd.Output()
	if err != nil {
		return "N/A"
	}
	return strings.TrimSpace(string(output))
}

func getGitCommit() string {
	cmd := exec.Command("git", "rev-parse", "HEAD")
	output, err := cmd.Output()
	if err != nil {
		return "N/A"
	}
	return strings.TrimSpace(string(output))
}
